bf16: true
cutoff_len: 4096
dataset: test_data
dataset_dir: data
ddp_timeout: 180000000
do_train: true
double_quantization: true
eval_steps: 100
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 1.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: D:\model\qwen2.5-7B-Instruct
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves\Qwen2.5-7B-Instruct\lora\train_2025-05-11-21-45-05
packing: false
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
quantization_bit: 4
quantization_method: bitsandbytes
report_to: none
rope_scaling: dynamic
save_steps: 100
stage: sft
template: qwen
trust_remote_code: true
val_size: 0.1
warmup_steps: 0
